// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcWAU9jSf5ypRLDYcTT1R6DZ_EvWsNJoE',
    appId: '1:946144161668:web:99c6229b3bc2ef2a6977d1',
    messagingSenderId: '946144161668',
    projectId: 'style-14c17',
    authDomain: 'style-14c17.firebaseapp.com',
    storageBucket: 'style-14c17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABFfWBA_SkGOl4w6Msmhee68Zjvf3hyQs',
    appId: '1:946144161668:android:eb9ab2ac78d443016977d1',
    messagingSenderId: '946144161668',
    projectId: 'style-14c17',
    storageBucket: 'style-14c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMu129eAcuzubtPcv3R-PiyjooOmN7HPY',
    appId: '1:946144161668:ios:771b42e318899a446977d1',
    messagingSenderId: '946144161668',
    projectId: 'style-14c17',
    storageBucket: 'style-14c17.firebasestorage.app',
    iosClientId: '946144161668-t70infal1ddhe5hnr4shoftv0u56e4eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.style',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMu129eAcuzubtPcv3R-PiyjooOmN7HPY',
    appId: '1:946144161668:ios:771b42e318899a446977d1',
    messagingSenderId: '946144161668',
    projectId: 'style-14c17',
    storageBucket: 'style-14c17.firebasestorage.app',
    iosClientId: '946144161668-t70infal1ddhe5hnr4shoftv0u56e4eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.style',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcWAU9jSf5ypRLDYcTT1R6DZ_EvWsNJoE',
    appId: '1:946144161668:web:c2b7f862144c256f6977d1',
    messagingSenderId: '946144161668',
    projectId: 'style-14c17',
    authDomain: 'style-14c17.firebaseapp.com',
    storageBucket: 'style-14c17.firebasestorage.app',
  );

}